
export enum AppState {
  GREETING = 'GREETING',
  NAME_INPUT = 'NAME_INPUT',
  WELCOME = 'WELCOME',
  MAILBOX = 'MAILBOX',
  LETTER_REVEAL = 'LETTER_REVEAL',
  PROPOSAL = 'PROPOSAL',
  ACCEPTED = 'ACCEPTED'
}
