
#:schema node_modules/wrangler/config-schema.json
name = "valentine-mailbox-surprise"

[build]
command = "npm run build"
path = "dist"

[vars]
# Environment variables can be defined here, or in the Cloudflare Dashboard
